const menuData = [
    {
        menu:"company",
        href:"#1",
        sub:null
    },
    {
        menu:"product",
        href:"#2",
        sub:[
            {
                smenu:"product1",
                href:"#pro1"
            },
            {
                smenu:"pro2",
                href:"#pro2"
            },
            {
                smenu:"pro3",
                href:"#pro3"
            },
            {
                smenu:"pro4",
                href:"#pro4"
            }
        ]
    },
    {
        menu:"community",
        href:"#3",
        sub:[
            {
                smenu:"com1",
                href:"#com1"
            },
            {
                smenu:"com2",
                href:"#com2"
            }
        ]
    },
    {
        menu:"board",
        href:"#4",
        sub:[
            {
                smenu:"board1",
                href:"#board1"
            },
            {
                smenu:"board2",
                href:"#board2"
            }
        ]
    },
    {
        menu:"online",
        href:"#5",
        sub:null
    }
    
]